name: Release

# Run workflow on commits to the `master` branch
on:
  push:
    tags:
      - 'RELEASE-**'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      MVN_OPT: -e
      BUILD_OPT: -Dmaven.test.skip=true
      DEPLOY_OPT: '-DMVN_REPO_USER_NAME=${{ secrets.nexus_username }} -DMVN_REPO_USER_PASSWORD=${{ secrets.nexus_password }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: ${{ secrets.nexus_username }}
          server-password: ${{ secrets.nexus_password }}

      - run: echo deploy into ${MVN_REPO_USER_NAME}@${MVN_REPO_URL_RELEASES}
      - run: cd dino-dependencies-root
      - run: echo "=============== 开始部署 dino-dependencies-root  ==============="
      - run: mvn clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
      - run: cd ..
