name: Publish package to the Maven Central Repository

# Run workflow on commits to the `master` branch
on:
  push:
    tags:
      - 'RELEASE-**'

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MVN_OPT: -e
      BUILD_OPT: '-Dmaven.test.skip=true -Possrh'
      DEPLOY_OPT: '-DMVN_REPO_USER_NAME=${{ secrets.NEXUS_USERNAME }} -DMVN_REPO_USER_PASSWORD=${{ secrets.NEXUS_PASSWORD }}'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: 'maven'
      - name: Install gpg secret key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg-private-key: ${{ secrets.NEXUS_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }}

      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo deploy into ${MVN_REPO_USER_NAME}@${MVN_REPO_URL_RELEASES}
          cd dino-dependencies-root
          echo "=============== 开始部署 dino-dependencies-root  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-assembly
          echo "=============== 开始部署 dino-spring-assembly  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-boot-starter-parent
          echo "=============== 开始部署 dino-spring-boot-starter-parent  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-cloud-starter-parent
          echo "=============== 开始部署 dino-spring-cloud-starter-parent  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-commons
          echo "=============== 开始部署 dino-spring-commons  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-data
          echo "=============== 开始部署 dino-spring-data  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-core
          echo "=============== 开始部署 dino-spring-core  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-auth
          echo "=============== 开始部署 dino-spring-auth  ==============="
          mvn --batch-mode -Dgpg.passphrase=${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }} clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
