name: Publish package to the Maven Central Repository

# Run workflow on commits to the `main` branch
on:
  push:
    tags: "RELEASE-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - error
          - warning
          - info


jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MVN_OPT: -e
      BUILD_OPT: "-Dmaven.test.skip=true"
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: "temurin"
          server-id: central
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          cache: "maven"

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish package
        run: |
          echo deploy into ${MVN_REPO_USER_NAME}@${MVN_REPO_URL_RELEASES}
          cd dino-dependencies-root
          echo "=============== 开始部署 dino-dependencies-root  ==============="
          mvn   deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-assembly
          echo "=============== 开始部署 dino-spring-assembly  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-boot-starter-parent
          echo "=============== 开始部署 dino-spring-boot-starter-parent  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-cloud-starter-parent
          echo "=============== 开始部署 dino-spring-cloud-starter-parent  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-commons
          echo "=============== 开始部署 dino-spring-commons  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-data
          echo "=============== 开始部署 dino-spring-data  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-core
          echo "=============== 开始部署 dino-spring-core  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
          cd dino-spring-auth
          echo "=============== 开始部署 dino-spring-auth  ==============="
          mvn --batch-mode  clean deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
          cd ..
