name: Publish package to the Maven Central Repository

# Run workflow on commits to the `main` branch
on:
  push:
    tags: "RELEASE-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - error
          - warning
          - info
          - debug
      autoPublish:
        description: "Auto publish"
        required: true
        default: true
        type: boolean
      waitUntil:
        description: "Wait until"
        required: true
        type: choice
        options:
          - published
          - uploaded
          - validated
      dino_dependencies_root:
        description: "Skip dependencies?"
        required: false
        type: boolean
      dino_spring_assembly:
        description: "Skip assembly?"
        required: false
        type: boolean
      dino_spring_boot_starter_parent:
        description: "Skip boot?"
        required: false
        type: boolean
      dino_spring_cloud_starter_parent:
        description: "Skip cloud?"
        required: false
        type: boolean
      dino_spring_commons:
        description: "Skip commons?"
        required: false
        type: boolean
      dino_spring_data:
        description: "Skip data?"
        required: false
        type: boolean
      dino_spring_auth:
        description: "Skip auth?"
        required: false
        type: boolean



jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      MVN_OPT: "--errors --no-transfer-progress --batch-mode"
      BUILD_OPT: "-Dmaven.test.skip=true -P publish"
      MVN_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      MVN_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      AUTO_PUBLISH: ${{ github.event.inputs.autoPublish || true }}
      WAIT_UNTIL: ${{ github.event.inputs.waitUntil }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: "temurin"
          server-id: central
          server-username: MVN_NEXUS_USERNAME
          server-password: MVN_NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: "maven"

      - name: Package & Install to Local Repository
        run: |
          touch /home/runner/.m2/settings-security.xml
          # 将secrets.MVN_SETTINGS_SECURITY写入到settings-security.xml文件
          echo "${{ secrets.MVN_SETTINGS_SECURITY }}" > /home/runner/.m2/settings-security.xml
          # 定义项目数组
          projects=(
            "dino-dependencies-root"
            "dino-spring-assembly"
            "dino-spring-boot-starter-parent"
            "dino-spring-cloud-starter-parent"
            "dino-spring-commons"
            "dino-spring-data"
            "dino-spring-auth"
            "dino-spring-core"
          )
          # 循环遍历项目数组
          for project in "${projects[@]}"; do
            # 进入项目目录
            cd "$project"
            # 输出开始打包信息
            echo "=============== 开始打包 $project ==============="
            # 执行mvn命令
            mvn clean package install $MVN_OPT $BUILD_OPT
            # 返回到上一级目录
            cd ..
          done

          echo "所有项目打包完成。"

      - name: Publish to Maven Central
        run: |
          echo "是否自动发布：$AUTO_PUBLISH"
          echo "等待条件：$WAIT_UNTIL"
          # 定义发布参数
          if [ "$AUTO_PUBLISH" = false ]; then
            export DEPLOY_AUTO_PUBLISH=false
            export DEPLOY_WAIT_UNTIL=${WAIT_UNTIL:-"uploaded"}
          else
            export DEPLOY_AUTO_PUBLISH=true
            export DEPLOY_WAIT_UNTIL=${WAIT_UNTIL:-"published"}
          fi

          # 从用户输入中获取skip_projects变量
          skip_projects=()
          if [ "${{ github.event.inputs.dino_dependencies_root }}" = true ]; then
            skip_projects+=("dino-dependencies-root")
          fi
          if [ "${{ github.event.inputs.dino_spring_assembly }}" = true ]; then
            skip_projects+=("dino-spring-assembly")
          fi
          if [ "${{ github.event.inputs.dino_spring_boot_starter_parent }}" = true ]; then
            skip_projects+=("dino-spring-boot-starter-parent")
          fi
          if [ "${{ github.event.inputs.dino_spring_cloud_starter_parent }}" = true ]; then
            skip_projects+=("dino-spring-cloud-starter-parent")
          fi
          if [ "${{ github.event.inputs.dino_spring_commons }}" = true ]; then
            skip_projects+=("dino-spring-commons")
          fi
          if [ "${{ github.event.inputs.dino_spring_data }}" = true ]; then
            skip_projects+=("dino-spring-data")
          fi
          if [ "${{ github.event.inputs.dino_spring_auth }}" = true ]; then
            skip_projects+=("dino-spring-auth")
          fi

          echo "=============== 开始发布到Maven中央仓库 ==============="
          # 定义项目数组
          projects=(
            "dino-dependencies-root"
            "dino-spring-assembly"
            "dino-spring-boot-starter-parent"
            "dino-spring-cloud-starter-parent"
            "dino-spring-commons"
            "dino-spring-data"
            "dino-spring-auth"
            "dino-spring-core"
          )
          # 循环遍历项目数组
          for project in "${projects[@]}"; do
            # 如果用户选择跳过当前项目，则跳过当前项目
            if [[ " ${skip_projects[@]} " =~ " $project " ]]; then
              echo "=============== 跳过发布 $project ==============="
              continue
            fi
            # 进入项目目录
            cd "$project"
            # 输出开始发布信息
            echo "=============== 开始发布 $project ==============="
            # 执行mvn命令
            mvn deploy $MVN_OPT $BUILD_OPT $DEPLOY_OPT
            # 返回到上一级目录
            cd ..
          done

          echo "所有项目发布完成。"
